# Generated by Django 5.1 on 2026-05-02 21:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("branch_id", models.CharField(max_length=20, unique=True)),
                ("name_ar", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("address", models.TextField(blank=True)),
                ("counters_total", models.IntegerField(default=8)),
                ("kiosks_total", models.IntegerField(default=4)),
                ("screens_total", models.IntegerField(default=3)),
                ("waiting_capacity", models.IntegerField(default=40)),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DigitalScreen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screen_id", models.CharField(max_length=10)),
                ("location_ar", models.CharField(max_length=100)),
                (
                    "current_content",
                    models.CharField(default="welcome_message", max_length=50),
                ),
                ("content_options", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screens",
                        to="branch.branch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kiosk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kiosk_id", models.CharField(max_length=10)),
                ("location_ar", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "متاح"),
                            ("in_use", "مستخدم"),
                            ("maintenance", "صيانة"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("services_supported", models.JSONField(default=list)),
                ("usage_today", models.IntegerField(default=0)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kiosks",
                        to="branch.branch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("employee_id", models.CharField(max_length=10, unique=True)),
                ("name_ar", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("senior_teller", "صراف رئيسي"),
                            ("teller", "صراف"),
                            ("relationship_manager", "مستشار علاقات"),
                            ("branch_manager", "مدير الفرع"),
                        ],
                        max_length=30,
                    ),
                ),
                ("counter", models.CharField(blank=True, max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("on_break", "في استراحة"),
                            ("on_leave", "في إجازة"),
                            ("off_duty", "خارج الدوام"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("avg_service_time_min", models.FloatField(default=5.0)),
                ("performance_score", models.FloatField(default=4.0)),
                ("customers_served_today", models.IntegerField(default=0)),
                ("experience_years", models.IntegerField(default=1)),
                ("break_started", models.DateTimeField(blank=True, null=True)),
                ("expected_return", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="branch.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["employee_id"],
            },
        ),
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("counter_type", models.CharField(default="general", max_length=20)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counters",
                        to="branch.branch",
                    ),
                ),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_counters",
                        to="branch.staff",
                    ),
                ),
            ],
        ),
    ]
