# Generated by Django 5.1 on 2026-05-08 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applicant_id', models.CharField(max_length=20, unique=True)),
                ('name_ar', models.CharField(max_length=120)),
                ('nationality', models.CharField(choices=[('saudi', 'مواطن سعودي'), ('resident', 'مقيم')], default='saudi', max_length=20)),
                ('age', models.IntegerField(default=35)),
                ('monthly_salary_sar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('existing_monthly_obligations_sar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employer_name', models.CharField(blank=True, max_length=120)),
                ('employer_sector', models.CharField(choices=[('government', 'حكومي'), ('private', 'قطاع خاص'), ('semi_government', 'شبه حكومي'), ('self_employed', 'عمل حر')], default='private', max_length=20)),
                ('employment_duration_months', models.IntegerField(default=24)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['applicant_id'],
            },
        ),
        migrations.CreateModel(
            name='MortgageApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_id', models.CharField(max_length=20, unique=True)),
                ('requested_loan_sar', models.DecimalField(decimal_places=2, max_digits=14)),
                ('requested_term_years', models.IntegerField(default=25)),
                ('property_source', models.CharField(choices=[('sakani', 'مشروع مُسَجَّل / Sakani'), ('independent', 'عقار مستقلّ')], default='sakani', max_length=20)),
                ('property_id', models.CharField(blank=True, max_length=40)),
                ('property_address', models.CharField(blank=True, max_length=255)),
                ('property_city', models.CharField(default='الرياض', max_length=60)),
                ('property_declared_price_sar', models.DecimalField(decimal_places=2, max_digits=14)),
                ('property_type', models.CharField(default='فيلا', max_length=60)),
                ('needs_general_support', models.BooleanField(default=False)),
                ('needs_legal_representative', models.BooleanField(default=False)),
                ('needs_accessibility', models.BooleanField(default=False)),
                ('accessibility_types', models.JSONField(default=list)),
                ('needs_translation', models.BooleanField(default=False)),
                ('needs_extended_consent', models.BooleanField(default=False)),
                ('needs_independent_advice', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'مسودّة'), ('docs_uploaded', 'المستندات مرفوعة'), ('screening_complete', 'فحص الدعم مكتمل'), ('under_review', 'قيد المراجعة'), ('review_complete', 'المراجعة منتهية')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='mortgage.applicant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation', models.CharField(choices=[('recommend_initial_approval', 'توصية بالموافقة الأوّلية'), ('recommend_approval_with_conditions', 'توصية بموافقة مشروطة'), ('needs_human_review', 'يحتاج مراجعة بشرية'), ('not_recommended', 'غير موصى بها')], max_length=50)),
                ('summary_per_agent', models.JSONField(default=dict)),
                ('conditions_if_any', models.JSONField(default=list)),
                ('residual_risks_for_human_review', models.JSONField(default=list)),
                ('binding', models.BooleanField(default=False)),
                ('demo_mode', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_recommendation', to='mortgage.mortgageapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('national_id', 'الهوية الوطنية'), ('salary_slip', 'تعريف بالراتب'), ('employment_letter', 'خطاب توظيف'), ('bank_statement', 'كشف حساب بنكي (٣ أشهر)'), ('property_deed', 'صك ملكية / عرض'), ('property_listing', 'بيان مشروع Sakani'), ('other', 'مستند آخر')], max_length=30)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='mortgage_docs/%Y/%m/')),
                ('file_size_bytes', models.IntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mortgage.mortgageapplication')),
            ],
            options={
                'ordering': ['kind', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('analytics', 'سارة — الجدارة الائتمانية'), ('operations', 'فهد — الهوية والقانوني'), ('customer', 'خالد — قدرة العميل والدعم'), ('queue', 'نورة — تقييم العقار'), ('orchestrator', 'المنسق — التوصية النهائية')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('structured', models.JSONField(blank=True, default=dict)),
                ('compliance_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mortgage.mortgageapplication')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
