# Generated by Django 5.1 on 2026-05-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('national_id', 'الهوية الوطنية'), ('salary_slip', 'تعريف بالراتب'), ('employment_letter', 'خطاب تعريف'), ('bank_statement', 'كشف حساب بنكي (٣ أشهر)'), ('property_deed', 'صك ملكية / عرض'), ('property_listing', 'بيان مشروع Sakani'), ('other', 'مستند آخر')], max_length=30),
        ),
    ]
