# Generated by Django 5.1 on 2026-05-02 21:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_id", models.CharField(max_length=10, unique=True)),
                ("name_ar", models.CharField(max_length=100)),
                ("alias", models.CharField(blank=True, max_length=50)),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("vip", "VIP"),
                            ("premium", "Premium"),
                            ("standard", "Standard"),
                        ],
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "annual_value_sar",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("avg_monthly_transactions", models.IntegerField(default=0)),
                ("preferred_services", models.JSONField(default=list)),
                ("visits_last_6m", models.IntegerField(default=0)),
                ("wait_tolerance_min", models.IntegerField(default=15)),
                ("satisfaction_score", models.FloatField(default=4.0)),
                ("nps_score", models.IntegerField(default=7)),
                (
                    "churn_risk",
                    models.CharField(
                        choices=[
                            ("very_low", "منخفض جداً"),
                            ("low", "منخفض"),
                            ("medium", "متوسط"),
                            ("high", "عالي"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                (
                    "preferred_channel",
                    models.CharField(default="WhatsApp", max_length=20),
                ),
                ("customer_since", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-annual_value_sar"],
            },
        ),
    ]
