# Generated by Django 5.1 on 2026-05-02 21:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branch", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("service_type", models.CharField(max_length=50)),
                ("is_simple", models.BooleanField(default=False)),
                ("ticket_number", models.IntegerField()),
                ("priority", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "منتظر"),
                            ("serving", "يخدم"),
                            ("completed", "مكتمل"),
                            ("redirected", "محول"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("wait_start", models.DateTimeField(auto_now_add=True)),
                ("serve_start", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("redirected_to_kiosk", models.BooleanField(default=False)),
                (
                    "assigned_counter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="branch.counter",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="branch.branch"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "wait_start"],
            },
        ),
        migrations.CreateModel(
            name="QueueSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("total_waiting", models.IntegerField()),
                ("total_serving", models.IntegerField()),
                ("avg_wait_minutes", models.FloatField()),
                ("max_wait_minutes", models.FloatField()),
                ("sla_compliance_percent", models.FloatField()),
                ("kiosk_usage_percent", models.FloatField(default=0)),
                ("staff_utilization_percent", models.FloatField(default=0)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="branch.branch"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SLAConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("segment", models.CharField(max_length=10)),
                ("max_wait_minutes", models.IntegerField()),
                ("penalty_sar", models.DecimalField(decimal_places=2, max_digits=8)),
                ("satisfaction_target", models.FloatField(default=4.5)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="branch.branch"
                    ),
                ),
            ],
            options={
                "unique_together": {("branch", "segment")},
            },
        ),
    ]
