# Generated by Django 5.1 on 2026-05-02 21:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("orchestrator", "المنسق"),
                            ("customer", "خالد — العملاء"),
                            ("queue", "نورة — الطوابير"),
                            ("operations", "فهد — العمليات"),
                            ("analytics", "سارة — التحليلات"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name_ar", models.CharField(max_length=50)),
                ("name_en", models.CharField(max_length=50)),
                ("role_ar", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=7)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "خامل"),
                            ("thinking", "يفكر"),
                            ("analyzing", "يحلل"),
                            ("sending", "يرسل"),
                            ("waiting", "منتظر"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                ("current_task", models.CharField(blank=True, max_length=200)),
                ("system_prompt", models.TextField()),
                (
                    "model_name",
                    models.CharField(
                        default="qwen/qwen-2.5-72b-instruct:free", max_length=100
                    ),
                ),
                ("temperature", models.FloatField(default=0.5)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["agent_type"],
            },
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scenario_id", models.CharField(max_length=10, unique=True)),
                ("name_ar", models.CharField(max_length=100)),
                ("name_en", models.CharField(blank=True, max_length=100)),
                (
                    "scenario_type",
                    models.CharField(
                        choices=[
                            ("routine", "روتيني"),
                            ("customer_request", "طلب عميل"),
                            ("operational_crisis", "أزمة تشغيلية"),
                            ("cultural", "ثقافي"),
                            ("opportunity", "فرصة"),
                            ("customer_crisis", "أزمة عميل"),
                            ("reporting", "تقارير"),
                        ],
                        max_length=20,
                    ),
                ),
                ("time", models.CharField(blank=True, max_length=10)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="⚡", max_length=5)),
                ("is_recommended", models.BooleanField(default=False)),
                ("tension_level", models.CharField(default="medium", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("use_ai", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["scenario_id"],
            },
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("decision_text", models.TextField()),
                ("reasoning", models.TextField()),
                (
                    "authority_level",
                    models.CharField(default="auto_approved", max_length=20),
                ),
                ("was_escalated", models.BooleanField(default=False)),
                ("outcome", models.TextField(blank=True)),
                (
                    "financial_impact_sar",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agents_consulted",
                    models.ManyToManyField(
                        blank=True,
                        related_name="consulted_decisions",
                        to="agents.agent",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="agents.scenario",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("to_broadcast", models.BooleanField(default=False)),
                ("content", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("alert", "تنبيه"),
                            ("analysis", "تحليل"),
                            ("suggestion", "اقتراح"),
                            ("decision", "قرار"),
                            ("update", "تحديث"),
                            ("question", "سؤال"),
                            ("confirmation", "تأكيد"),
                        ],
                        default="update",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "حرج"),
                            ("high", "عالي"),
                            ("medium", "متوسط"),
                            ("low", "منخفض"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_ai_generated", models.BooleanField(default=False)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("delay_ms", models.IntegerField(default=1500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="agents.agent",
                    ),
                ),
                (
                    "to_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="agents.agent",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="agents.scenario",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
    ]
