# Generated by Django 5.1 on 2026-05-02 21:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branch", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_ar", models.CharField(max_length=200)),
                ("body_ar", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "معلومة"),
                            ("warning", "تحذير"),
                            ("critical", "حرج"),
                            ("opportunity", "فرصة"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="branch.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ar", models.CharField(max_length=100)),
                ("key", models.CharField(max_length=50)),
                ("value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("target", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis",
                        to="branch.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("customers_served", models.IntegerField(default=0)),
                ("avg_wait_minutes", models.FloatField(default=0)),
                ("sla_compliance_percent", models.FloatField(default=0)),
                ("satisfaction_score", models.FloatField(default=0)),
                ("self_service_percent", models.FloatField(default=0)),
                ("decisions_made", models.IntegerField(default=0)),
                (
                    "sar_saved",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to="branch.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("branch", "date")},
            },
        ),
    ]
